dependencies:
  - name: elasticsearch
    repository: https://kubernetes-charts.storage.googleapis.com/
    version: 1.15.1
    condition: useElasticsearch
  - name: memcached
    version: 2.4.0
    repository: https://kubernetes-charts.storage.googleapis.com/
    condition: useMemcached
  - name: postgresql
    version: 3.7.0
    repository: https://kubernetes-charts.storage.googleapis.com/
    condition: usePostgresql
